extends: "eslint:recommended"
env:
  browser: true
  es2021: true
  webextensions: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-prototype-builtins: off
  no-unused-vars:
    - error
    - vars: local
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
