image: alpine:latest

pages:
  stage: deploy
  script:
    - mv data public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - data/**/*
