image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -a src/hide_rules src/param_cleaning src/click_whitelist .public/
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
